version: '3.8'
services:
  # React App
  app:
    image: node:8.18-alpine
    container_name: agucor_fe
    volumes:
      - ./:/app
    working_dir: /app
    ports:
        - 3001:3000
    command: npm run start
    tty: true
